// Code generated by scripts/import-metodichka.mjs; DO NOT EDIT.
package main

var teacherCourseLessons = []string{
	"python-basics-input-output",
	"python-basics-types-arithmetic",
	"python-basics-div-mod-digits",
	"python-basics-logic",
	"python-branches-if-else",
	"python-branches-elif-ranges",
	"python-branches-compound",
	"python-debugging-basics",
	"python-loops-while",
	"python-loops-for-range",
	"python-loops-nested",
	"python-loops-accumulators",
	"python-loops-min-max-average",
	"python-loops-sequences",
	"python-loops-tracing",
	"python-strings-basics",
	"python-strings-methods-slices",
	"python-strings-algorithms",
	"python-strings-runs",
	"python-lists-basics",
	"python-lists-mutation",
	"python-lists-processing",
	"python-lists-linear-search",
	"python-lists-neighbours",
	"python-lists-2d",
	"python-lists-matrices",
	"python-collections-sets",
	"python-collections-dicts-frequency",
	"python-collections-stack-queue",
	"python-functions-basics",
	"python-functions-scope-decomposition",
	"python-recursion-basics",
	"python-recursion-calculations",
	"python-files-basics",
	"python-files-numbers",
	"python-files-text",
	"python-algorithms-binary-search",
	"python-algorithms-selection-sort",
	"python-algorithms-python-sort",
	"python-numbers-divisibility-divisors",
	"python-numbers-primes-gcd",
	"python-numbers-bases",
	"python-brute-force-basics",
	"python-complexity-basics",
	"python-dp-basics",
	"python-graphs-basics",
	"python-graphs-traversal",
	"python-graphs-paths",
	"python-graphs-dijkstra",
}

const teacherCourseExerciseCount = 239

var teacherCoursePracticums = []struct {
	ID string
	Title string
	Total int
}{
	{ID: "python-practicum-first-programs", Title: "Практикум 1. Первые программы", Total: 12},
	{ID: "python-practicum-loops", Title: "Практикум 2. Циклы", Total: 15},
	{ID: "python-practicum-data", Title: "Практикум 3. Строки и структуры данных", Total: 17},
	{ID: "python-practicum-functions-files", Title: "Практикум 4. Функции, рекурсия и файлы", Total: 12},
	{ID: "python-practicum-algorithms", Title: "Практикум 5. Алгоритмы", Total: 15},
	{ID: "python-practicum-final", Title: "Практикум 6. Итоговый", Total: 21},
}
